### ISSUE TITLE
main feature

### ISSUE THREAD

**Issue by devbyP** [devbyP/macfix-web#2]
# Todo
- Pages layout
  - [ ] request page
  - [ ] term condition page
  - [ ] waiting page
  - [ ] worker reply page (confirm or cancel)
  - [ ] progress page
  - [ ] done and pick up page
  - [ ] rate page
 
- [ ] Mock up test
 
- Functionality
  - [ ] Step to step page transition
  - [ ] request validation and requirement
  - [ ] image upload delete
  - [ ] wait worker response
  - [ ] link to delivery site or app
  - [ ] rate after service
  - [ ] confirm order (order assign to database when confirm to worker to work on)
  - [ ] progress and status update when worker update
  - notification on ios app
    - [ ] when worker reply
    - [ ] when work done
  - [ ] confirm picker after work done
  - [ ] delivery info when select delivery picke up

**Comment by devbyP** [comment]
progress, done and pickup move to status feature.
